version: '3.1'

services:
  mongo:
    image: mongo:3.6
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data/db
  proxy:
    build: server/
    restart: always
    ports:
      - 80:80